branch-defaults:
  default:
    environment: flask-env
    group_suffix: null
environment-defaults:
  flask-env:
    branch: null
    repository: null
global:
  application_name: flask-tutorial
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
